/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentation;

import Logic.Game_Logic;
import static Logic.Game_Logic.Reset_Table;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;

/**
 *
 * @author jerem
 */
public class PrincipalP extends javax.swing.JFrame {

    public static int Row = 3;
    public static int Col = 3;
    JButton[][] Buttons_Array;

    public PrincipalP() {
        initComponents();
        Load_Buttons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Panel_Juego = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Turno_Lbl = new javax.swing.JLabel();
        Btn_Reiniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Juego.setPreferredSize(new java.awt.Dimension(510, 420));

        javax.swing.GroupLayout Panel_JuegoLayout = new javax.swing.GroupLayout(Panel_Juego);
        Panel_Juego.setLayout(Panel_JuegoLayout);
        Panel_JuegoLayout.setHorizontalGroup(
            Panel_JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        Panel_JuegoLayout.setVerticalGroup(
            Panel_JuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        jPanel1.add(Panel_Juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jLabel1.setText("Turno del jugador:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 6, -1, -1));

        Turno_Lbl.setText("0");
        jPanel1.add(Turno_Lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 28, -1, -1));

        Btn_Reiniciar.setText("Reiniciar");
        Btn_Reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReiniciarActionPerformed(evt);
            }
        });
        jPanel1.add(Btn_Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(534, 403, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 637, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReiniciarActionPerformed
         Reset_Table(Buttons_Array);
    }//GEN-LAST:event_Btn_ReiniciarActionPerformed

    private void Load_Buttons() {
        Buttons_Array = new JButton[Row][Col];

        int x = 50;
        int y = 50;

        for (int i = 0; i < Row; i++) {
            for (int j = 0; j < Col; j++) {
                Buttons_Array[i][j] = new JButton();
                Buttons_Array[i][j].setBackground(Color.LIGHT_GRAY);
                Buttons_Array[i][j].setBounds(x, y, 120, 120);
                Buttons_Array[i][j].setEnabled(true);
                Buttons_Array[i][j].setMnemonic('a');// Alt + Letra
                Buttons_Array[i][j].setForeground(Color.BLUE); // Color Letra
                Buttons_Array[i][j].setFont(new Font("Tahoma", Font.BOLD, 70));
                Buttons_Array[i][j].setName("Boton" + String.valueOf(i) + String.valueOf(i));

                Panel_Juego.add(Buttons_Array[i][j]);

                x += 120;
            }
            x = 50;
            y += 120;
        }
        Game_Logic.Set_Place(Buttons_Array, Turno_Lbl);

    }
//    private void Player() {
//    int Actual_User = 1;
//    
//    if (Actual_User == 1) {
//        Turno_Lbl.setText(text);
//    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Reiniciar;
    private javax.swing.JPanel Panel_Juego;
    private javax.swing.JLabel Turno_Lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
